ASSETS_PATH = "assets/images/menu/"
STATE_PATH = "assets/state.txt"

TAMANHO = 68.75

POSICOES_TABULEIRO = {
    'A8':(TAMANHO*0,TAMANHO*0), 'B8':(TAMANHO*1,TAMANHO*0), 'C8':(TAMANHO*2,TAMANHO*0), 'D8':(TAMANHO*3,TAMANHO*0), 'E8':(TAMANHO*4,TAMANHO*0), 'F8':(TAMANHO*5,TAMANHO*0), 'G8':(TAMANHO*6,TAMANHO*0), 'H8':(TAMANHO*7,TAMANHO*0),
    'A7':(TAMANHO*0,TAMANHO*1), 'B7':(TAMANHO*1,TAMANHO*1), 'C7':(TAMANHO*2,TAMANHO*1), 'D7':(TAMANHO*3,TAMANHO*1), 'E7':(TAMANHO*4,TAMANHO*1), 'F7':(TAMANHO*5,TAMANHO*1), 'G7':(TAMANHO*6,TAMANHO*1), 'H7':(TAMANHO*7,TAMANHO*1),
    'A6':(TAMANHO*0,TAMANHO*2), 'B6':(TAMANHO*1,TAMANHO*2), 'C6':(TAMANHO*2,TAMANHO*2), 'D6':(TAMANHO*3,TAMANHO*2), 'E6':(TAMANHO*4,TAMANHO*2), 'F6':(TAMANHO*5,TAMANHO*2), 'G6':(TAMANHO*6,TAMANHO*2), 'H6':(TAMANHO*7,TAMANHO*2),      
    'A5':(TAMANHO*0,TAMANHO*3), 'B5':(TAMANHO*1,TAMANHO*3), 'C5':(TAMANHO*2,TAMANHO*3), 'D5':(TAMANHO*3,TAMANHO*3), 'E5':(TAMANHO*4,TAMANHO*3), 'F5':(TAMANHO*5,TAMANHO*3), 'G5':(TAMANHO*6,TAMANHO*3), 'H5':(TAMANHO*7,TAMANHO*3),
    'A4':(TAMANHO*0,TAMANHO*4), 'B4':(TAMANHO*1,TAMANHO*4), 'C4':(TAMANHO*2,TAMANHO*4), 'D4':(TAMANHO*3,TAMANHO*4), 'E4':(TAMANHO*4,TAMANHO*4), 'F4':(TAMANHO*5,TAMANHO*4), 'G4':(TAMANHO*6,TAMANHO*4), 'H4':(TAMANHO*7,TAMANHO*4),
    'A3':(TAMANHO*0,TAMANHO*5), 'B3':(TAMANHO*1,TAMANHO*5), 'C3':(TAMANHO*2,TAMANHO*5), 'D3':(TAMANHO*3,TAMANHO*5), 'E3':(TAMANHO*4,TAMANHO*5), 'F3':(TAMANHO*5,TAMANHO*5), 'G3':(TAMANHO*6,TAMANHO*5), 'H3':(TAMANHO*7,TAMANHO*5),
    'A2':(TAMANHO*0,TAMANHO*6), 'B2':(TAMANHO*1,TAMANHO*6), 'C2':(TAMANHO*2,TAMANHO*6), 'D2':(TAMANHO*3,TAMANHO*6), 'E2':(TAMANHO*4,TAMANHO*6), 'F2':(TAMANHO*5,TAMANHO*6), 'G2':(TAMANHO*6,TAMANHO*6), 'H2':(TAMANHO*7,TAMANHO*6),
    'A1':(TAMANHO*0,TAMANHO*7), 'B1':(TAMANHO*1,TAMANHO*7), 'C1':(TAMANHO*2,TAMANHO*7), 'D1':(TAMANHO*3,TAMANHO*7), 'E1':(TAMANHO*4,TAMANHO*7), 'F1':(TAMANHO*5,TAMANHO*7), 'G1':(TAMANHO*6,TAMANHO*7), 'H1':(TAMANHO*7,TAMANHO*7),
}

POSICOES_TABULEIRO_LISTA = [
    [(TAMANHO*0,TAMANHO*7), (TAMANHO*1,TAMANHO*7), (TAMANHO*2,TAMANHO*7), (TAMANHO*3,TAMANHO*7), (TAMANHO*4,TAMANHO*7), (TAMANHO*5,TAMANHO*7), (TAMANHO*6,TAMANHO*7), (TAMANHO*7,TAMANHO*7)],
    [(TAMANHO*0,TAMANHO*6), (TAMANHO*1,TAMANHO*6), (TAMANHO*2,TAMANHO*6), (TAMANHO*3,TAMANHO*6), (TAMANHO*4,TAMANHO*6), (TAMANHO*5,TAMANHO*6), (TAMANHO*6,TAMANHO*6), (TAMANHO*7,TAMANHO*6)],
    [(TAMANHO*0,TAMANHO*5), (TAMANHO*1,TAMANHO*5), (TAMANHO*2,TAMANHO*5), (TAMANHO*3,TAMANHO*5), (TAMANHO*4,TAMANHO*5), (TAMANHO*5,TAMANHO*5), (TAMANHO*6,TAMANHO*5), (TAMANHO*7,TAMANHO*5)],      
    [(TAMANHO*0,TAMANHO*4), (TAMANHO*1,TAMANHO*4), (TAMANHO*2,TAMANHO*4), (TAMANHO*3,TAMANHO*4), (TAMANHO*4,TAMANHO*4), (TAMANHO*5,TAMANHO*4), (TAMANHO*6,TAMANHO*4), (TAMANHO*7,TAMANHO*4)],
    [(TAMANHO*0,TAMANHO*3), (TAMANHO*1,TAMANHO*3), (TAMANHO*2,TAMANHO*3), (TAMANHO*3,TAMANHO*3), (TAMANHO*4,TAMANHO*3), (TAMANHO*5,TAMANHO*3), (TAMANHO*6,TAMANHO*3), (TAMANHO*7,TAMANHO*3)],
    [(TAMANHO*0,TAMANHO*2), (TAMANHO*1,TAMANHO*2), (TAMANHO*2,TAMANHO*2), (TAMANHO*3,TAMANHO*2), (TAMANHO*4,TAMANHO*2), (TAMANHO*5,TAMANHO*2), (TAMANHO*6,TAMANHO*2), (TAMANHO*7,TAMANHO*2)],
    [(TAMANHO*0,TAMANHO*1), (TAMANHO*1,TAMANHO*1), (TAMANHO*2,TAMANHO*1), (TAMANHO*3,TAMANHO*1), (TAMANHO*4,TAMANHO*1), (TAMANHO*5,TAMANHO*1), (TAMANHO*6,TAMANHO*1), (TAMANHO*7,TAMANHO*1)],
    [(TAMANHO*0,TAMANHO*0), (TAMANHO*1,TAMANHO*0), (TAMANHO*2,TAMANHO*0), (TAMANHO*3,TAMANHO*0), (TAMANHO*4,TAMANHO*0), (TAMANHO*5,TAMANHO*0), (TAMANHO*6,TAMANHO*0), (TAMANHO*7,TAMANHO*0)]
]

COLUNAS = dict({'A': 0, 'B': 1, 'C': 2, 'D': 3, 'E': 4, 'F': 5, 'G': 6, 'H': 7})

COLUNAS_STR = "ABCDEFGH"
